#specify environment variables

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: locph02032003/master:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  type: NodePort
  selector:
    app: master
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
      - name: slave
        image: locph02032003/slave:latest
        env:
        - name: MASTER_HOST
          value: "master"
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        ports:
        - containerPort: 3306     
---
apiVersion: v1
kind: Service
metadata:
  name: slave
spec:
  type: ClusterIP
  selector:
    app: slave
  ports:
    - port: 3306
      targetPort: 3306